---
version: 2
updates:

  # GitHub actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    labels:
      - automation
      - dependabot
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
