name: updatecli
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  updatecli:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - if: github.ref == 'refs/heads/main'
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.V1V_UPDATECLI_BOT_APP_ID }}
          private-key: ${{ secrets.V1V_UPDATECLI_BOT_APP_PRIVKEY }}

      - uses: actions/checkout@v4

      - uses: updatecli/updatecli-action@9b35aa663a924d5d5faf89dac76594e3034bcf1f  # v2.56.0
        with:
          version: "v0.76.0-rc.1"

      - run: updatecli compose diff
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: github.ref == 'refs/heads/main'
        run: updatecli compose apply
        env:
          GITHUB_ACTOR: ${{ secrets.V1V_UPDATECLI_BOT_GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
